version: "2.18"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=Home_File_Server
      - POSTGRES_DB=HFS_Db
    volumes:
      - D:/data/pgdata:/var/lib/postgresql/data
    ports:
      - "5342:5432"

  rust_rocket:
    depends_on:
      - db
    build: .
    volumes:
      - D:/data/home-file-server:/data
    ports:
      - 8000:8000
